[all:vars]
ansible_user=enz
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3

[kube_control_plane]
node1 ansible_host=35.247.128.44 ansible_connection=local
node2 ansible_host=34.47.116.146  # ip=10.3.0.2 etcd_member_name=etcd2
node3 ansible_host=34.47.118.166  # ip=10.3.0.3 etcd_member_name=etcd3

[etcd:children]
kube_control_plane

[kube_node]
node4 ansible_host=34.50.1.143  # ip=10.3.0.4
node5 ansible_host=34.22.107.114  # ip=10.3.0.5
# node6 ansible_host=95.54.0.17  # ip=10.3.0.6
